### ISSUE TITLE
Change the title from "Commands" to something shorter

### ISSUE THREAD

**Issue by fedkad** [StorageB/custom-command-menu#2]
To save space, I would like to change the title of the menu (**Commands**) to something shorter, like **Cmds** or even **⌘**.

A configuration setting to allow this will be highly appreciated.

Currently, I am replacing all strings like `'Commands'` in the **.js** files to something else to achieve this purpose.

**Comment by StorageB** [comment]
I'll try to get this added to the next version. 

For now, you only need to change the "Commands" text in one location in the extension.js file as shown below in order to change the title. In the code is also instructions on how to swap out the text for an icon.

![Screenshot from 2024-09-10 22-09-53](https://github.com/user-attachments/assets/141eb82a-880f-4ba2-bccf-419cac5fe326)

**Comment by StorageB** [comment]
This feature has been added. There is now an option to use either custom text or a custom icon as the menu title. Thanks for the suggestion!
